# Generated by Django 4.0.4 on 2022-04-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_works', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zadanie',
            new_name='Zadania',
        ),
    ]
