# Generated by Django 4.0.4 on 2022-04-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_works', '0002_rename_zadanie_zadania'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zadania',
            new_name='Task',
        ),
    ]
